POST https://api.mercadopago.com/instore/orders/qr/seller/collectors/1457339680/pos/UNIC2IDENTIFICATOR123/qrs
Authorization: Bearer APP_USR-7885482239406684-083115-a74d92ed4eedb4dbb2a4c3813eb64df0-1457339680
Content-Type: application/json
Content-Length: 485
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
x-http2-scheme: https

{
  "cash_out": {
    "amount": 0
  },
  "description": "Descripción de la compra",
  "external_reference": "random123",
  "items": [
    {
      "sku_number": "A123K9191938",
      "category": "marketplace",
      "title": "Point Mini",
      "description": "ddffgg",
      "unit_price": 15,
      "quantity": 1,
      "unit_measure": "unit",
      "total_amount": 15
    }
  ],
  "notification_url": "https://www.cualquersitio.com/",
  "title": "Test order3",
  "total_amount": 15
}

<> 2024-11-23T043156.201.json

###

POST https://api.mercadopago.com/instore/orders/qr/seller/collectors/1457339680/pos/UNIC2IDENTIFICATOR123/qrs
Authorization: Bearer APP_USR-7885482239406684-083115-a74d92ed4eedb4dbb2a4c3813eb64df0-1457339680
Content-Type: application/json
Content-Length: 485
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
x-http2-scheme: https

{
  "cash_out": {
    "amount": 0
  },
  "description": "Descripción de la compra",
  "external_reference": "random123",
  "items": [
    {
      "sku_number": "A123K9191938",
      "category": "marketplace",
      "title": "Point Mini",
      "description": "ddffgg",
      "unit_price": 15,
      "quantity": 1,
      "unit_measure": "unit",
      "total_amount": 15
    }
  ],
  "notification_url": "https://www.cualquersitio.com/",
  "title": "Test order3",
  "total_amount": 15
}

<> 2024-11-23T043020.201.json

###

POST https://api.mercadopago.com/instore/orders/qr/seller/collectors/1457339680/pos/UNIC2IDENTIFICATOR123/qrs
Authorization: Bearer APP_USR-7885482239406684-083115-a74d92ed4eedb4dbb2a4c3813eb64df0-1457339680
Content-Type: application/json
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
x-http2-scheme: https
Content-Length: 485

{
  "cash_out": {
    "amount": 0
  },
  "description": "Descripción de la compra",
  "external_reference": "random123",
  "items": [
    {
      "sku_number": "A123K9191938",
      "category": "marketplace",
      "title": "Point Mini",
      "description": "ddffgg",
      "unit_price": 15,
      "quantity": 1,
      "unit_measure": "unit",
      "total_amount": 15
    }
  ],
  "notification_url": "https://www.cualquersitio.com/",
  "title": "Test order3",
  "total_amount": 15
}

<> 2024-11-23T042438.201.json

###

POST https://api.mercadopago.com/instore/orders/qr/seller/collectors/1457339680/pos/UNIC2IDENTIFICATOR123/qrs
Authorization: Bearer APP_USR-7885482239406684-083115-a74d92ed4eedb4dbb2a4c3813eb64df0-1457339680
Content-Type: application/json
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
x-http2-scheme: https
Content-Length: 485

{
  "cash_out": {
    "amount": 0
  },
  "description": "Descripción de la compra",
  "external_reference": "random123",
  "items": [
    {
      "sku_number": "A123K9191938",
      "category": "marketplace",
      "title": "Point Mini",
      "description": "ddffgg",
      "unit_price": 15,
      "quantity": 1,
      "unit_measure": "unit",
      "total_amount": 15
    }
  ],
  "notification_url": "https://www.cualquersitio.com/",
  "title": "Test order3",
  "total_amount": 15
}

<> 2024-11-23T042413.201.json

###

POST https://api.mercadopago.com/instore/orders/qr/seller/collectors/1457339680/pos/UNIC2IDENTIFICATOR123/qrs
Authorization: Bearer APP_USR-7885482239406684-083115-a74d92ed4eedb4dbb2a4c3813eb64df0-1457339680
Content-Type: application/json
Content-Length: 485
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
x-http2-scheme: https

{
  "cash_out": {
    "amount": 0
  },
  "description": "Descripción de la compra",
  "external_reference": "random123",
  "items": [
    {
      "sku_number": "A123K9191938",
      "category": "marketplace",
      "title": "Point Mini",
      "description": "ddffgg",
      "unit_price": 15,
      "quantity": 1,
      "unit_measure": "unit",
      "total_amount": 15
    }
  ],
  "notification_url": "https://www.cualquersitio.com/",
  "title": "Test order3",
  "total_amount": 15
}

<> 2024-11-22T033930.201.json

###

POST https://api.mercadopago.com/instore/orders/qr/seller/collectors/1457339680/pos/UNIC2IDENTIFICATOR123/qrs
Authorization: Bearer APP_USR-7885482239406684-083115-a74d92ed4eedb4dbb2a4c3813eb64df0-1457339680
Content-Type: application/json
Content-Length: 485
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
x-http2-scheme: https

{
  "cash_out": {
    "amount": 0
  },
  "description": "Descripción de la compra",
  "external_reference": "random123",
  "items": [
    {
      "sku_number": "A123K9191938",
      "category": "marketplace",
      "title": "Point Mini",
      "description": "ddffgg",
      "unit_price": 15,
      "quantity": 1,
      "unit_measure": "unit",
      "total_amount": 15
    }
  ],
  "notification_url": "https://www.cualquersitio.com/",
  "title": "Test order3",
  "total_amount": 15
}

<> 2024-11-22T024100.201.json

###

